### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by myozka** [Fmakdemir/f-qr-fixer#3]
What changes did you do during the past 6 months or so? Anything I can work on?

**Comment by Fmakdemir** [comment]
Patched it up for SECCON with a one nighter :) tests/fixes/new ideas would be very nice

**Comment by myozka** [comment]
I don't know what this code is capable of. We planned lot of features, which of those are implemented?

**Comment by Fmakdemir** [comment]
- QR reading except for kanji mode.
- QR fixing with missing positionings.
- QR fixing with data part intact.

TODO:
- QR fixing when data part is missing.
- QR orientation detection based on timing lines.

On Sun, Feb 14, 2016 at 4:59 AM, myozka <notifications@github.com> wrote:

> I don't know what this code is capable of. We planned lot of features,
> which of those are implemented?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fmakdemir/f-qr-fixer/issues/3#issuecomment-183809011>.
>



-- 
Furkan Mustafa Akdemir
Bilkent University-Computer Science
